名字: 建筑
在:
  workflow_dispatch:
输入:
        package_name:
描述: “游戏包名称：”
所需: 真正的

工作:
建筑:
    runs-on: ubuntu-latest
步骤:
    - 用途: actions/checkout@v4
    - 用途: actions/setup-java@v4
与:
分布: 铁木林
        java-version: 11
贮存物: gradle
    - 跑: |
chmod +x ./gradlew
sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
./gradlew：模块：汇编释放
    - 用途: actions/upload-artifact@v4
与:
名字: zygisk-il2cppdumper
路径: out/magisk_module_release/
